server:
  port: 8000

web:
  domain: http://localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
